# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
 - name: ACCELQ Github-A Connect
  # You may pin to the exact commit or the version.
  # uses: accelq/accelq-ci-github-actions@2686194162077054ea3d1f227dc8fb8b0d2eb3d5
  uses: accelq/accelq-ci-github-actions@v1.4
  with:
    # Your ACCELQ Application URL in the exact following format: https://<hostname>:<port_num>
    appURL: "https://poc.accelq.io/"
    # Your ACCELQ User ID
    userName: "ajay@accelq.com"
    # API key available in Profile section of ACCELQ
    apiKey: "iR7dnnxsqk1jByNNJRUCY4ywwZWeqXJVUp_H41IrA_8"
    # Tenant Code displayed in the Profile section of ACCELQ
    tenantCode: "poc"
    # This ID should come from the CI job you saved in ACCELQ application
    jobId: "434522"
    # Run Params(optional) should be JSON string form example: '{"username": "John Todd", "password": "bxW&=UVw"}'
    runParam: # optional
    # Proxy Host (optional)
    proxyHost: # optional
    # Proxy Port (optional)
    proxyPort: # optional
    # Percentage ACCELQ test case failure (Optional), beyond which this Step in the Pipeline will be marked as a failure. If this is zero, even a single failed test will cause the Step to fail. If you never want to fail the Pipeline Step due to failing Automation tests, input -1. Input a valid integer between 0 and 100 or, -1.
    stepFailureThreshold: # optional
    # Maximum time to wait for the job to be picked up by an ACCELQ Agent. Default is 15 mins.
    maxWaitTimeInMins: # optional
